### PR TITLE
Create 06-06-2021-council-meeting-notes.md

### PR DESCRIPTION
**Pull request by stakervali**
Created a folder named "notes".
Added meeting notes for 06 June 2021.

### CODE REVIEW

**Review by MCM-Mike — APPROVED** [review]
Its a good start to have meeting notes. 
We can later discuss a different design or some formatting changes to a template we can always use.

**Comment by davidtavarez** [comment]
This is awesome!

**Review by davidtavarez — APPROVED** [review]

**Comment by MCM-Mike** [comment]
Based on https://github.com/grincc/docs/blob/main/approval-scheme.md I will merge it now

**Review by Anynomouss — APPROVED** [review]
Looks good to me

**Comment by MCM-Mike** [comment]
I think we need to open this PR again @stakervali the date is not correct, the meeting notes where for the https://github.com/grincc/agenda/issues/1 22.06.2021 not 06.06.2021 which is todays meeting.

**Comment by stakervali** [comment]
Sorry, I noticed just after submitting. I have submitted the correction with  7 July's meeting notes PR.

**Pull request merged**
